---
abstract: 'Build structures from CGI data. Fast.'
author:
  - 'Dmitry Smal <mialinx@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.132140'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CGI-Struct-XS
no_index:
  directory:
    - t
    - inc
requires:
  Storable: 0
  Test::Deep: 0
  Test::Deep::NoTest: 0
  Test::LeakTrace: 0
  Test::More: 0
  XSLoader: 0
version: 1.04
