--- #YAML:1.0
name:               CGI-Struct-XS
version:            1.02
abstract:           Build structures from CGI data. Fast.
author:
    - Dmitry Smal <mialinx@gmail.com>
license:            bsd
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    Test::Deep:          0
    Test::Deep::NoTest:  0
    Test::LeakTrace:     0
    Test::More:          0
requires:
    Storable:  0
    XSLoader:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.57_05
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
